# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o linkedList.o test.o Problem1.o Problem2.o Problem3.o Problem4.o Problem5.o Problem6.o Problem7.o $(RES)
LINKOBJ  = main.o linkedList.o test.o Problem1.o Problem2.o Problem3.o Problem4.o Problem5.o Problem6.o Problem7.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Project1.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "Project1.exe" $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

linkedList.o: linkedList.c
	$(CC) -c linkedList.c -o linkedList.o $(CFLAGS)

test.o: test.c
	$(CC) -c test.c -o test.o $(CFLAGS)

Problem1.o: Problem1.c
	$(CC) -c Problem1.c -o Problem1.o $(CFLAGS)

Problem2.o: Problem2.c
	$(CC) -c Problem2.c -o Problem2.o $(CFLAGS)

Problem3.o: Problem3.c
	$(CC) -c Problem3.c -o Problem3.o $(CFLAGS)

Problem4.o: Problem4.c
	$(CC) -c Problem4.c -o Problem4.o $(CFLAGS)

Problem5.o: Problem5.c
	$(CC) -c Problem5.c -o Problem5.o $(CFLAGS)

Problem6.o: Problem6.c
	$(CC) -c Problem6.c -o Problem6.o $(CFLAGS)

Problem7.o: Problem7.c
	$(CC) -c Problem7.c -o Problem7.o $(CFLAGS)
